version: "3.8"
services:
  postgres_local:
    image: postgres:12.13-alpine
    container_name: "postgres-local"
    ports:
      - '5432:5432'
    volumes:
      - /Users/multani/HomeProjects/idea/readyToStart/DockerStartUps/postgresDocker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: localPostgres